theme: jekyll-theme-cayman
google_analytics: UA-136790987-1
title: RSS Feeds Articles

site_favicon: favicon.ico

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

github:
  is_project_page: false
  
twitter:
  username: jimit105
  card: summary
  
social:
  name: Jimit Dholakia
  links:
    - https://www.linkedin.com/in/jimit105/
    - https://github.com/jimit105
    - https://medium.com/@jimit105
    
author:
  twitter: jimit105
